version: "3.7"
services:
  mariadb:
    image: mariadb:10.7
    container_name: user-api-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PackageDB
    ports:
      - "3306:3306"