version: "3.7"
services:
  mariadb:
    image: mariadb:10.8.3
    container_name: McPackage-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PackageDB
    ports:
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock