version: "3.7"
services:
  mysql:
    image: mariadb:10.8.3
    container_name: McPackage-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PackageDB
    ports:
      - "3306:3306"